Repository msandfor/10-Easy-Steps, pull requests merged in 2020-10, with the labels that each got.

#67 Learn most popular php framework
  README.md
Labels: documentation :memo:, hacktoberfest :children_crossing:, on-hold

#253 Updated the Python Community Entry in the Get Involved Section
  README.md
Labels: hacktoberfest-accepted

#267 Edit FreeCodeCamp Podcast comment
  README.md
Labels: hacktoberfest-accepted

#268 Added Python for Beginners to the YouTube Section
  README.md
Labels: hacktoberfest-accepted

#269 Add Quantum Katas to the And Then What? Section for issue #264
  README.md
Labels: hacktoberfest-accepted

#276 Updated the Youtube section of the Readme.md file
  README.md
Labels: hacktoberfest-accepted

#284 Added resource to Free tools
  README.md
Labels: hacktoberfest-accepted

#291 commit for issue #262
  README.md
Labels: invalid :alien:

#294 Update README.md for issue #234
  README.md
Labels: hacktoberfest-accepted

#306 Update README.md
  README.md
Labels: hacktoberfest-accepted

#307 Update README.md
  README.md
Labels: hacktoberfest-accepted

#308 Update README.md
  README.md
Labels: hacktoberfest-accepted

#310 Updated learn code academy text
  README.md
Labels: hacktoberfest-accepted

#311 Update README.md
  README.md
Labels: hacktoberfest-accepted

#312 Adding Coding Train to YouTube Section
  README.md
Labels: hacktoberfest-accepted

#313 Update the Learn in One Video entry
  README.md
Labels: hacktoberfest-accepted

#315 Update LearnCode.academy entry
  README.md
Labels: hacktoberfest-accepted
